### ISSUE TITLE
Jazzy support timeline

### ISSUE THREAD

**Issue by istvan-fodor** [sequenceplanner/r2r#104]
Hi! Thanks for working on this project!

Is there a timeline for releasing Jazzy support? I saw the [PR](https://github.com/sequenceplanner/r2r/pull/100) , sounds like there it is good to go.

Thank you!

**Comment by m-dahl** [comment]
Hi.

Yes it should just be to do a release I think. I had ambitions to do some more before making a new release but I have been too busy with other stuff lately so I just forgot about it. Let me check the status of things and I can do a new release shortly.

**Comment by m-dahl** [comment]
It's released now. Sorry it took so long!

**Comment by istvan-fodor** [comment]
Thank you!
