### ISSUE TITLE
Don't you use cargo fmt?

### ISSUE THREAD

**Issue by OTL** [sequenceplanner/r2r#11]
It seems that the source of r2r is not formated by rustfmt.
I think it's very popular to use `cargo fmt` to format the files.

**Comment by m-dahl** [comment]
Yes I really should use it. I also want to run the generated code through rustfmt. Will leave this open so that I get around to it eventually.

**Comment by kristoferB** [comment]
We should fix it in the futures branch before merging with master...

**Comment by m-dahl** [comment]
There is now a rustfmt.toml but maybe we should also automate a check so we don't forget to run it

**Comment by raimannma** [comment]
There should be a pre commit hook

**Comment by m-dahl** [comment]
Cleaning up some old issues.
