### ISSUE TITLE
Will there be support for rmw_zenoh?

### ISSUE THREAD

**Issue by playerdefault** [sequenceplanner/r2r#113]
rmw_zenoh is gaining traction. r2r uses C introspection libraries for discovering message types, and these libraries are only required for DDS (because the IDL generator generates them for communicating with the DDS middleware). I don't think zenoh_rmw will need these (as it's not DDS) which can lead to breakage of functionality of r2r.

So, will r2r support zenoh_rmw?

**Comment by m-dahl** [comment]
Hi,

I quickly tried rmw_zenoh with r2r and it works out of the box. ([Here](https://github.com/ros2/rmw_zenoh/blob/rolling/docs/design.md#serializationdeserialization) you can read that the serialization format is still the same). I don't know if they are planning on doing anything different in the long run?

Happy to take a look if you encounter problems with it.
