### ISSUE TITLE
Widestring issue during cargo build

### ISSUE THREAD

**Issue by leeds9446** [sequenceplanner/r2r#114]
I got this build error on the second step.
First: source /opt/ros/humble/setup.sh
Second: cargo build -> error

error[E0433]: failed to resolve: use of undeclared crate or module `widestring`
  --> /home/dev/lidar_ws/Rust_Websocket/r2r/target/debug/build/r2r-95b225250fa983fd/out/rclrs_example_msgs.rs:16:26
   |
16 |         pub wchar_value: widestring::WideChar,
   |                          ^^^^^^^^^^ use of undeclared crate or module `widestring`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `r2r` (lib) due to 1 previous error

Is this issue only happening to me? I'm using Ubuntu 22.04 with the latest patch and rust version 1.82.0 (f6e511eec 2024-10-15).

**Comment by m-dahl** [comment]
Hi,

Thanks for the report. It seems you hit a code path no one else has hit before and of course there was a bug in it :) I have pushed what I hope is a fix and made a new release. Please reopen if the problem remains.
