### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by m-dahl** [sequenceplanner/r2r#12]
Set up CI that continuously builds and runs the tests on rolling and foxy. Add galactic when that is released. Would be enough to run on ubuntu at the moment.

**Comment by m-dahl** [comment]
Could you take a look @kristoferB

**Comment by kristoferB** [comment]
Yes i can set it up. I will deploy my dockerfiles including ros and rust to dockerhub and then i can set up the actions for this.
