### ISSUE TITLE
WrappedTypesupport private

### ISSUE THREAD

**Issue by aboseley** [sequenceplanner/r2r#31]
I got stuck today trying to write a generic node subscribe function  because the `WrappedTypesupport` trait is private. All the ROS types I was using implemented this trait because they were auto-generated messages type.  So this feels like something I should be able to do, but was blocked unnecessarily

**Comment by kristoferB** [comment]
Good suggestion. When do you plan to implement this trait manually?

**Comment by lopsided98** [comment]
I'm running into the same problem with `WrappedServiceTypeSupport`. I'm not implementing the trait manually; I would like to write a function that takes a generic service `Client` as a parameter, like this:
```rust
fn some_function<T: r2r::msg_types::WrappedServiceTypeSupport>(client: r2r::Client<T>) {
}
```

**Comment by m-dahl** [comment]
I agree that it would be useful. I will take a look at this next week. Should be a simple fix.

**Comment by m-dahl** [comment]
Hi. These should now be accessible in 0.6.5.
