### ISSUE TITLE
Release request (may be v0.7.0) to crate.io

### ISSUE THREAD

**Issue by OTL** [sequenceplanner/r2r#35]
I want to use the latest change to avoid the problem of the names of the fields.
https://github.com/sequenceplanner/r2r/commit/1955bdda3bb8da9878f793e53b714634375292fd

I know that we can use `git` in `Cargo.toml`, but it's better to use the released version to release a crate.

**Comment by kristoferB** [comment]
Hi. We will do a new release after the holidays...

**Comment by m-dahl** [comment]
Hi, I just released 0.6.4 based on the latest commit. Sorry it took so long. Please reopen this if I introduced any errors. I intend to work through the open issues and PRs next week and make a new release after that.

**Comment by OTL** [comment]
Thanks a lot!
Happy holidays!👍
