### ISSUE TITLE
Compile only necessary packages to speed up compilation

### ISSUE THREAD

**Issue by jerry73204** [sequenceplanner/r2r#53]
Currently, r2r compiles all discovered message types, which leads to a lengthy compilation time.
The idea is to let r2r acknowledge required ROS packages in `package.xml` (or `Cargo.toml`), and compile necessary packages.
The tricky part is to allow `r2r` to learn requested packages from dependent crates. It is usually done by feature flags or environment variables. A relevant discussion can be found here rust-lang/cargo#4121.

**Comment by m-dahl** [comment]
Hi.

We have this though I realize it is not well documented. You can see a note about it under "building with cargo" [here](https://github.com/m-dahl/r2r_minimal_node#building-using-only-cargo). 

It is just a crude filter so it does not know about dependencies, so if you have nested message types you need to explicitly include all of the packages you use.

If you use the colcon way of building it will also only build the requested packages. I hope this helps.

**Comment by jerry73204** [comment]
How does r2r discover requested packages when using colcon? Just curious.

**Comment by jerry73204** [comment]
Thanks for your explanation. This feature should be well documented in README. It helps reducing lots of compilation time.

**Comment by m-dahl** [comment]
Added to readme as per your suggestion, thanks.
