### ISSUE TITLE
Failed docs.rs build

### ISSUE THREAD

**Issue by rdelfin** [sequenceplanner/r2r#55]
The latest published version of r2r has [a failed docs.rs build](https://docs.rs/crate/r2r/0.7.1/builds). I suspect this failiure will be present in future versions too unless the bug was fixed. Is it worth having a CI check in this repo to confirm this?

**Comment by m-dahl** [comment]
Good catch. Yes its easy to forget without CI. I will add it.

**Comment by m-dahl** [comment]
Fixed in 0.7.3. Thanks!

**Comment by rdelfin** [comment]
Thanks for the quick fix!
