### ISSUE TITLE
Get publisher infos by topic 

### ISSUE THREAD

**Issue by NerdToMars** [sequenceplanner/r2r#78]
Hi there,

I have a use case where I have to use some publishers info, such as topic type, qos profile

notice r2r already has rcl_get_publishers_info_by_topic binding, it  would be nice to have a get_publishers_info_by_topic function under Node struct. 

here are the generic cpp version to get the topic endpoint info: https://github.com/ros2/rclcpp/blob/2bb1dc2c716ae12a24145891724f8436aa4e52bd/rclcpp/src/rclcpp/node_interfaces/node_graph.cpp#L663

I'm happy to try and implement this for r2r, just wondering if there is any concern I should to be aware of ..

Thanks!

**Comment by m-dahl** [comment]
Hi, 

I don't think there really much to think about, I would say just go ahead and try to implement it if you need the functionality. I will try to support if you have any questions, you can open a PR for it.

**Comment by m-dahl** [comment]
Fixed in #80
