### ISSUE TITLE
How to create a new r2r::builtin_interfaces::msg::Time to represent the current timestamp? I can't seem to find fn

### ISSUE THREAD

**Issue by xiaocijun** [sequenceplanner/r2r#79]

**Comment by m-dahl** [comment]
I assume you found `Clock::to_builtin_time` since you closed the issue? It's in a weird place, someday I will move it :)

**Comment by xiaocijun** [comment]
> I assume you found `Clock::to_builtin_time` since you closed the issue? It's in a weird place, someday I will move it :) 

ok
