### ISSUE TITLE
sensor_msgs cannot found

### ISSUE THREAD

**Issue by Necro-U** [sequenceplanner/r2r#86]
Hello I am trying to use sensor_msgs, Intellisense can read the sensor_msgs but when i try to build it with colcon it issues about sensor_msgs. I added sensor_msgs into config.toml but still it is not working.

The error : 

error[E0433]: failed to resolve: could not find `sensor_msgs` in `r2r`
  --> ahrar/src/data.rs:14:10
   |
14 | use r2r::sensor_msgs::msg::Image;
   |          ^^^^^^^^^^^ could not find `sensor_msgs` in `r2r`

Config.toml :

IDL_PACKAGE_FILTER = { value = "std_msgs;geometry_msgs;sensor_msgs;px4_msgs" }

By the way i have tried to build it with cargo build, first it complained about geometry_msgs after adding it into IDL_PACKAGE_FILTER, errors gone for cargo.

**Comment by m-dahl** [comment]
Hi. I would guess that you don't have sensor_msgs in `CMakeLists.txt` (in the `r2r_cargo` function call).

**Comment by Necro-U** [comment]
yeah I also found that sorry i forgot to close issue
