### ISSUE TITLE
ROS2 Jazzy support

### ISSUE THREAD

**Issue by des256** [sequenceplanner/r2r#99]
Hi, I'm using r2r with ROS2 Jazzy, but this is not yet officially supported. Can I just go ahead and fix the issues myself, and then open a pull request here to help r2r? What is your preferred procedure for this?

Best,
Desmond.

**Comment by m-dahl** [comment]
Hi Desmond,

Nice, I didn't notice Jazzy was out. A PR that adds Jazzy support would be very welcome!
